kpfu/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'kpfu_plan.views.login', name='index'),
    url(r'^min-edu/', include('min_obr.urls'), name='min-edu'),
    url(r'^plan/', include('kpfu_plan.urls'), name='plan'),

    # system urls
    url(r'^login/', 'kpfu_plan.views.login', name="login"),
    url(r'^logout/$', 'kpfu_plan.views.logout', name='logout'),
]

min_obr/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^(?P<subject_id>[0-9]+)$', 'min_obr.views.new', name='new'),


    # points ajax request
    url(r'^point/(?P<subject_id>[0-9]+)/(?P<point_id>[0-9]+)/$', 'min_obr.views.point_service', name='point-service'),
]

min_obr/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.db import models
import os

def get_goal_doc_url(instance, filename):
    return os.path.join('goal_docs', filename)


class CompetenceTrainees(models.Model):
    cipher = models.CharField(max_length=50)
    decryption = models.CharField(max_length=255)
    edu = models.ForeignKey('MinistryOfEdu', db_column='edu')
    additional = models.BooleanField()
    spec_id = models.IntegerField(null=True)

    class Meta:
        db_table = 'competence_trainees'


class Description(models.Model):
    author = models.TextField(blank=True, null=True)
    external_author = models.BooleanField()
    reviewers = models.TextField(blank=True, null=True)
    external_reviewers = models.BooleanField()
    min_edu = models.ForeignKey('MinistryOfEdu')

    class Meta:
        db_table = 'description'


class InternetResource(models.Model):
    name = models.CharField(max_length=255)
    link = models.CharField(max_length=255)
    min_edu = models.ForeignKey('MinistryOfEdu')

    class Meta:
        db_table = 'internet_resource'


class MinistryOfEdu(models.Model):
    goals_disciplines = models.TextField(blank=True, null=True)
    goals_document = models.FileField(blank=True, upload_to=get_goal_doc_url)
    posistion_disciplines = models.TextField(blank=True, null=True)
    edu_technology = models.TextField()
    # TODO: devide main and additional literature for capability to add docs
    main_literature = models.TextField(blank=True, null=True, max_length=255)
    additional_literature = models.TextField(blank=True, null=True, max_length=255)
    six_other = models.TextField(blank=True, null=True, max_length=255)
    eight_other = models.TextField(blank=True, null=True, max_length=255)

    class Meta:
        db_table = 'ministry_of_edu'


class StructureAndContent(models.Model):
    discipline = models.TextField(null=True)
    semester = models.IntegerField(null=True)
    week_of_semester = models.CharField(max_length=10, null=True)
    lecture = models.IntegerField(blank=True, null=True)
    practice = models.IntegerField(blank=True, null=True)
    labs = models.IntegerField(blank=True, null=True)
    self_work = models.IntegerField(null=True)
    control_type = models.CharField(max_length=2, null=True)
    content = models.TextField(blank=True, null=True)
    monitoring_progress = models.TextField(null=True)
    min_edu = models.ForeignKey(MinistryOfEdu)
    spec_id = models.IntegerField(null=True)
    test = models.CharField(null=True, max_length=255)
    homework = models.CharField(null=True, max_length=255)

    class Meta:
        db_table = 'structure_and_content'


class SelfTime(models.Model):
    type_self_work = models.TextField(null=True)
    time = models.IntegerField(null=True)
    control_form = models.TextField(null=True)
    structure = models.ForeignKey(StructureAndContent, null=True)
    spec_id = models.IntegerField(null=True)

    class Meta:
        db_table = 'self_time'


class Support(models.Model):
    is_enable = models.BooleanField(default=False)
    min_edu = models.ForeignKey(MinistryOfEdu)
    spec_id = models.IntegerField(null=True)

    class Meta:
        db_table = 'support'


class UserAndSubject(models.Model):
    user = models.ForeignKey(User, null=False)
    minEdu = models.ForeignKey(MinistryOfEdu, null=True)
    subject = models.CharField(max_length=255, null=True)

    class Meta:
        db_table = 'user_and_subject'

min_obr/views.py
# coding=utf-8
from django.contrib.auth.decorators import login_required
from django.db.models import QuerySet
from django.http import HttpResponse
from django.shortcuts import render, render_to_response

# Create your views here.
from django.template import RequestContext

from min_obr.models import MinistryOfEdu, UserAndSubject, CompetenceTrainees, StructureAndContent, SelfTime, Support


@login_required(login_url="/login")
def new(request, subject_id):
    return render(request, 'min_obr/index.html', {})


def point_service(request, subject_id, point_id):
    points = {
        0: zero,
        1: one,
        2: two,
        3: three,
        4: four,
        5: five,
        6: six,
        7: seven,
        8: eight,
        # add more
    }
    subject = UserAndSubject.objects.get(id=subject_id)
    if subject.minEdu is None:
        minister_of_edu = MinistryOfEdu()
        minister_of_edu.save()
        subject.minEdu = minister_of_edu
        subject.save()
        response = points[int(point_id)](request, subject=subject, min_edu=minister_of_edu)
    else:
        minister_of_edu = MinistryOfEdu.objects.get(id=subject.minEdu.id)
        response = points[int(point_id)](request, subject=subject, min_edu=minister_of_edu)
    return response if type(response) == HttpResponse else HttpResponse(status=200)


def zero(request):
    pass


def one(request, min_edu, subject):
    context = RequestContext(request)
    if request.method == 'POST':
        try:
            min_edu.goals_disciplines = request.POST.get('p_goal')
            min_edu.save()
        except KeyError:
            pass

        try:
            min_edu.goals_document = request.FILES.get('file')
            min_edu.save()
        except KeyError:
            pass
    else:
        return (render_to_response("min_obr/forms/point-1.html",
                                   {'minEdu': min_edu},
                                   context
                                   ))


def two(request, min_edu, subject):
    context = RequestContext(request)
    if request.method == 'POST':
        min_edu.posistion_disciplines = request.POST.get('posistionDisciplines')
        min_edu.save()
    else:
        return (render_to_response("min_obr/forms/point-2.html",
                                   {'minEdu': min_edu},
                                   context
                                   ))


def three(request, min_edu, subject):
    context = RequestContext(request)
    if request.method == "POST":
        competence_trainees = CompetenceTrainees.objects.filter(edu=min_edu.id,
                                                                spec_id=int(request.POST.get("spec_id")))
        additional = False if int(request.POST.get('spec_id')) != 0 else True
        if len(competence_trainees) == 0:
            competence_trainees = CompetenceTrainees(additional=additional,
                                                     edu=subject.minEdu,
                                                     spec_id=request.POST.get('spec_id'))
            if request.POST.get("type") == "select":
                competence_trainees.cipher = request.POST.get('value')
            else:
                competence_trainees.decryption = request.POST.get("value")
            competence_trainees.save()
        else:
            for i in competence_trainees:
                if i.spec_id == int(request.POST.get('spec_id')):
                    if request.POST.get("type") == "select":
                        i.cipher = request.POST.get('value')
                    else:
                        i.decryption = request.POST.get("value")
                    i.save()
    else:
        competence_trainees = CompetenceTrainees.objects.filter(edu=min_edu.id)
        return (render_to_response("min_obr/forms/point-3.html",
                                   {
                                       'minEdu': min_edu,
                                       'competence': competence_trainees
                                   },
                                   context))


def four(request, min_edu, subject):
    context = RequestContext(request)
    if request.method == 'POST':
        structure_and_content = StructureAndContent.objects.filter(min_edu=min_edu,
                                                                   spec_id=int(request.POST.get('specId')))
        if len(structure_and_content) == 0:
            structure_and_content = StructureAndContent(min_edu=min_edu)
            structure_and_content.spec_id = request.POST.get('specId')

        if type(structure_and_content) == QuerySet:
            structure_and_content = structure_and_content.first()
        if 'infoSpecId' not in request.POST:
            setattr(structure_and_content, request.POST.get('columnName'), request.POST.get('value'))
            structure_and_content.save()
        else:
            self_time = SelfTime.objects.filter(structure=structure_and_content,
                                                spec_id=int(request.POST.get('specId')))
            if len(self_time) == 0:
                self_time = SelfTime(structure=structure_and_content,
                                     spec_id=int(request.POST.get('specId')))
            if type(self_time) == QuerySet:
                self_time = self_time.first()
            setattr(self_time, request.POST.get('columnName'), request.POST.get('value'))
            self_time.save()
    elif request.method == 'DELETE':
        structure_and_content = StructureAndContent.objects.get(min_edu=min_edu,
                                                                spec_id=int(request.DELETE.get('specId')))
        if structure_and_content is not None:
            if request.DELETE.get('infoSpecId') is not None:
                try:
                    self_time = SelfTime.objects.get(structure=structure_and_content,
                                                     spec_id=int(request.DELETE.get('specId')))
                except SelfTime.DoesNotExist:
                    self_time = None
                if self_time is not None:
                    self_time.delete()
            else:
                structure_and_content.delete()
    elif request.method == 'GET':
        structure_and_content = StructureAndContent.objects.filter(min_edu=min_edu)
        return (render_to_response("min_obr/forms/point-4.html",
                                   {'structure_and_content': structure_and_content},
                                   context
                                   ))


def five(request, min_edu, subject):
    context = RequestContext(request)
    if request.method == 'POST':
        min_edu.edu_technology = request.POST.get("value")
        min_edu.save()
    else:
        return (render_to_response("min_obr/forms/point-5.html",
                                   {'minEdu': min_edu},
                                   context
                                   ))


def six(request, min_edu, subject):
    context = RequestContext(request)
    structure_and_content = StructureAndContent.objects.filter(min_edu=min_edu, control_type__isnull=False)
    if request.method == 'POST':
        if request.POST.get('type') == 'other':
            min_edu.six_other = request.POST.get('value')
            min_edu.save()
        else:
            structure = StructureAndContent.objects.get(id=request.POST.get('fconId'))
            if request.POST.get('type') == 'h':
                structure.homework = request.POST.get('value')
            else:
                structure.test = request.POST.get('value')
            structure.save()

    else:
        return (render_to_response("min_obr/forms/point-6.html",
                                   {'rows': structure_and_content,
                                    'minEdu': min_edu},
                                   context
                                   ))


def seven(request, min_edu, subject):
    context = RequestContext(request)
    if request.method == 'POST':
        setattr(min_edu, request.POST.get('type'), request.POST.get('value'))
        min_edu.save()
    else:
        return (render_to_response("min_obr/forms/point-7.html",
                                   {'minEdu': min_edu},
                                   context
                                   ))


def eight(request, min_edu, subject):
    context = RequestContext(request)
    if request.method == 'POST':
        if request.POST.get('type') == 'other':
            min_edu.eight_other = request.POST.get('value')
            min_edu.save()
        else:
            try:
                support = Support.objects.get(min_edu=min_edu, spec_id=request.POST.get('spec_id'))
            except Support.DoesNotExist:
                support = None
            if support is None:
                support = Support(min_edu=min_edu,
                                  spec_id=request.POST.get('spec_id'),
                                  is_enable=request.POST.get('value'))
                support.save()
            else:
                if request.POST.get('value') == 'false':
                    support.delete()

    else:
        supports = Support.objects.filter(min_edu=min_edu)
        return (render_to_response("min_obr/forms/point-8.html",
                                   {'minEdu': min_edu,
                                    'supports': supports},
                                   context
                                   ))

min_obr/templates/min_obr/forms/point-1.html
<legend>1. Цели освоения дисциплины</legend>
<div class="form-group is-empty">

    <div class="col-md-12">
        <textarea class="form-control p-goals" name="p-goals"
                  rows="5">{{ minEdu.goals_disciplines|default_if_none:"" }}</textarea>

        <label>*Вы можете так же добавить презентацию курса (не обязательное поле)
            <input type="file" name="goal-doc" class="form-control p-goals-doc"></label>
    </div>
</div>

min_obr/templates/min_obr/forms/point-2.html
<legend>2. Место дисциплины в структуре основной образовательной программы высшего профессионального
    образования по направлению
    09.03.03 Прикладная информатика
</legend>
<div class="form-group is-empty">

    <div class="col-md-12">
        <textarea class="form-control posistion-disciplines"
                  rows="5">{{ minEdu.posistion_disciplines|default_if_none:"" }}</textarea>
    </div>
</div>

min_obr/templates/min_obr/forms/point-3.html
{% load utils %}
<legend>3. Компетенции обучающегося, формулируемые в результате освоения дисциплины/модуля</legend>
<label for="form-group">Обязательная компетенция</label>

<div class="competence">
    <div class="mandatory-competence">
        {% for i in "12345" %}
            <div class="form-group is-empty">

                <label for="select-{{ i }}" class="col-md-2 control-label">Шифр компетенции</label>

                <div class="col-md-2">
                    <select id="select-{{ i }}" class="form-control">
                        <option {% find_selected competence i -1 'selected' %} disabled></option>
                        <option {% find_selected competence i 1 'selected' %} >1</option>
                        <option {% find_selected competence i 2 'selected' %} >2</option>
                        <option {% find_selected competence i 3 'selected' %} >3</option>
                        <option {% find_selected competence i 4 'selected' %} >4</option>
                        <option {% find_selected competence i 5 'selected' %} >5</option>
                    </select>

                </div>
                <label for="textarea-{{ i }}" class="col-md-2 control-label">Расшифровка приобретаемой
                    компетенции</label>


                <div class="col-md-6">
                    <textarea class="form-control" id="textarea-{{ i }}" rows="5">{% get_decryption competence i %}</textarea>
                </div>

            </div>
        {% endfor %}
    </div>
    <label for="form-group">Дополнительная компетенция</label>

    <div class="form-group is-empty">

        <label for="select-0" class="col-md-2 control-label">Шифр компетенции</label>

        <div class="col-md-2">
            <select id="select-0" class="form-control">
                <option {% find_selected competence 0 -1 'selected' %}>1</option>
                <option {% find_selected competence 0 1 'selected' %}>2</option>
                <option {% find_selected competence 0 2 'selected' %}>3</option>
                <option {% find_selected competence 0 3 'selected' %}>4</option>
                <option {% find_selected competence 0 4 'selected' %}>5</option>
            </select>

        </div>
        <label for="textarea-0" class="col-md-2 control-label">Расшифровка приобретаемой
            компетенции</label>

        <div class="col-md-6">
            <textarea class="form-control" id="textarea-0" rows="5">{% get_decryption competence 0 %}</textarea>
        </div>
    </div>
</div>

min_obr/templates/min_obr/forms/point-4.html
{% load utils %}
<legend>4. Структура и содержание аудиторной работы по дисциплине/модулю
</legend>
<div class="form-group is-empty">

    <div class="col-md-12 time-info">

        <!--                        div.panel-body>table.table.ralbe-bordered>(thead>(tr>th[rowspan="2"]{Семестр, в котром читается дисциплина}+th[rowspan="2"]{Общая трудоемкость дисциплины(в зачетных единицах)}+th[colspan="4"]{Общая трудовемкость дисциплины(в часах)}+th[rowspan="2"]{Всего часов на сомостоятельную работу}+th[rowspan="2"]{Форма контроля})+(tr>th{Всего}+th{Лекционных часов}+th{практических занятий}+th{лабораторных работ}))+tbody>(tr>td{План (согласно утверженному учебному плану)})+(tr>td{Факт(согласно введенной заполняющим в настоящее время информации)})+(tr>td{Остаток нераспределенных часов})-->
        <div class="panel-body">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th rowspan="2"></th>
                    <th rowspan="2">Семестр, в котром читается дисциплина</th>
                    <th rowspan="2">Общая трудоемкость дисциплины(в зачетных единицах)</th>
                    <th colspan="4">Общая трудовемкость дисциплины(в часах)</th>
                    <th rowspan="2">Всего часов на сомостоятельную работу</th>
                    <th rowspan="2">Форма контроля</th>
                </tr>
                <tr>
                    <th>Всего</th>
                    <th>Лекционных часов</th>
                    <th>практических занятий</th>
                    <th>лабораторных работ</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>План (согласно утверженному учебному плану)</td>
                </tr>
                <tr>
                    <td>Факт(согласно введенной заполняющим в настоящее время информации)</td>
                </tr>
                <tr>
                    <td>Остаток нераспределенных часов</td>
                </tr>
                </tbody>
            </table>
        </div>


    </div>
    <div>
        <div class="panel-body">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th width="20px" rowspan="2">#</th>
                    <th rowspan="2">
                        Разделы дисциплины <br>
                        Название
                        (не более 4000 символов)
                    </th>
                    <th rowspan="2">Семестр</th>
                    <th rowspan="2">Недели семестра</th>
                    <th colspan="3">Виды и часы аудиторной работы</th>
                    <th rowspan="2">Часы самостоятельной работы</th>
                    <th rowspan="2" width="200px">Текущие формы контроля</th>
                </tr>
                <tr>
                    <th>лекция</th>
                    <th>практическое занятие</th>
                    <th>лабораторное занятие</th>
                </tr>

                </thead>
                <tbody>
                {% if structure_and_content.all|length == 0 %}
                    {% include 'min_obr/forms/point-4_main_blank.html' %}
                {% else %}
                    {% for struct in structure_and_content.all %}
                        <tr class="js-main-row">
                            <input type="hidden" class="js-main-row-id" value="1">
                            <td>
                                <input class="table-num form-control" type="number" value="1" disabled>
                                <button class="form-control remove-row" type="button"><i
                                        class="glyphicon glyphicon-remove"></i></button>
                                <button type="button" class="form-control additionally-info"><i
                                        class="glyphicon glyphicon-pencil"></i></button>
                            </td>
                            <td><textarea class="form-control table-discipline" name="discipline"
                                          rows="4">{{ struct.discipline|default_if_none:'' }}</textarea></td>
                            <td>
                                <select class="form-control table-semester" name="semester">
                                    <option disabled {% get_selection_by_id struct.semester -1 %}></option>
                                    <option value="1" {% get_selection_by_id struct.semester 1 %}>1</option>
                                    <option value="2" {% get_selection_by_id struct.semester 2 %}>2</option>
                                    <option value="3" {% get_selection_by_id struct.semester 3 %}>3</option>
                                    <option value="4" {% get_selection_by_id struct.semester 4 %}>4</option>
                                    <option value="5" {% get_selection_by_id struct.semester 5 %}>5</option>
                                    <option value="6" {% get_selection_by_id struct.semester 6 %}>6</option>
                                    <option value="7" {% get_selection_by_id struct.semester 7 %}>7</option>
                                    <option value="8" {% get_selection_by_id struct.semester 8 %}>8</option>
                                </select>
                            </td>
                            <td><input type="number" class="form-control table-week-semester"
                                       name="week_of_semester" value="{{ struct.week_of_semester|default_if_none:'' }}">
                            </td>
                            <td>0</td>
                            <td><input type="number" class="form-control table-prac-les"
                                       name="practice" value="{{ struct.practice|default_if_none:'' }}"></td>
                            <td>1</td>
                            <td><input type="number" class="form-control table-self-work"
                                       name="self_work" value="{{ struct.self_work|default_if_none:'' }}"></td>
                            <td>
                                <select class="form-control table-form-control" name="control_type">
                                    <option disabled {% get_selection_by_id struct.control_type -1 %}></option>
                                    <option value="0" {% get_selection_by_id struct.control_type 0 %}>Домашнее задание
                                    </option>
                                    <option value="1" {% get_selection_by_id struct.control_type 1 %}>Контрольная работа
                                    </option>
                                    <option value="2" {% get_selection_by_id struct.control_type 2 %}>Домашняя и
                                        контрольная
                                        работа
                                    </option>
                                </select>
                            </td>
                        </tr>

                        <tr style="display: none;" class="js-additional-row">
                            <input type="hidden" class="js-add-row-id" value="1">
                            <td colspan="9">
                                <div class="content">
                                    <div class="sec-cont">
                                        <label for="section-сontents" style="width: 30%;">Содержание раздела
                                            <br>
                                            Развернутое содержание раздела (темы) с указанием дидактических
                                            единиц</label>
                                    <textarea name="content" class="section-сontents form-control"
                                              rows="5">{{ struct.content|default_if_none:'' }}</textarea>
                                    </div>
                                    <br>
                                    {% if struct.selftime_set.all|length == 0 %}
                                        {% include 'min_obr/forms/point-4_add_blank.html' %}
                                    {% else %}
                                        {% for self_time in struct.selftime_set.all %}
                                            <div class="add-info">
                                                <input type="hidden" class="js-add-info-id" value="1">
                                                <div class="type-self-work">
                                                    <label for="type-self-work">Виды Самостоятельной работы</label>
                                        <textarea name="type_self_work" class="js-selfwork-type form-control"
                                                  rows="3">{{ self_time.type_self_work|default_if_none:'' }}</textarea>
                                                </div>
                                                <div class="hour">
                                                    <label for="hour">Часы</label>
                                                    <input type="number" name="time" class="js-hour form-control"
                                                           value="{{ self_time.time|default_if_none:'' }}">
                                                    <div class="btn-group add-info-btns">
                                                        <button class="btn btn-default new-add-info" type="button"><i
                                                                class="glyphicon glyphicon-plus"></i></button>
                                                        <button class="btn btn-default remove-add-info" type="button"><i
                                                                class="glyphicon glyphicon-remove"></i></button>
                                                    </div>
                                                </div>
                                                <div class="control-work">
                                                    <label for="control-work">Формы контроля самостоятельной
                                                        работы</label>
                                        <textarea name="control_form" class="js-control-form form-control"
                                                  rows="3">{{ self_time.control_form|default_if_none:'' }}</textarea>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </td>
                        </tr>

                    {% endfor %}
                {% endif %}
                </tbody>
            </table>
            <button id="add-new-row" type="button" class="form-control col-md-10">Добавить еще</button>
        </div>
    </div>
</div>

min_obr/templates/min_obr/forms/point-4_add_blank.html
<div class="add-info">
    <input type="hidden" class="js-add-info-id" value="1">
    <div class="type-self-work">
        <label for="type-self-work">Виды Самостоятельной работы</label>
                                        <textarea name="type_self_work" class="js-selfwork-type form-control"
                                                  rows="3"></textarea>
    </div>
    <div class="hour">
        <label for="hour">Часы</label>
        <input type="number" name="time" class="js-hour form-control">
        <div class="btn-group add-info-btns">
            <button class="btn btn-default new-add-info" type="button"><i
                    class="glyphicon glyphicon-plus"></i></button>
            <button class="btn btn-default remove-add-info" type="button"><i
                    class="glyphicon glyphicon-remove"></i></button>
        </div>
    </div>
    <div class="control-work">
        <label for="control-work">Формы контроля самостоятельной
            работы</label>
                                        <textarea name="control_form" class="js-control-form form-control"
                                                  rows="3"></textarea>
    </div>
</div>

min_obr/templates/min_obr/forms/point-5.html
<legend>5. Образовательные технологии, включая инерактивные формы обучения
</legend>
<div class="edu-tech">
    <textarea name="edu-tech" class="form-control" id="edu-tech-textarea" cols="30" rows="10">{{ minEdu.edu_technology|default_if_none:'' }}</textarea>
</div>

min_obr/templates/min_obr/forms/point-7.html
<legend>7. Литература и ресурсы
</legend>
<div class="literature">
    <div class="main-literature">
        <label for="main-literature">Основная литература</label>
        <textarea name="main_literature" class="form-control" rows="10">{{ minEdu.main_literature|default_if_none:"" }}</textarea>
    </div>
    <div class="additional-literature">
        <label for="additional-literature">Дополнительная литература</label>
        <textarea name="additional_literature" class="form-control"
                  rows="10">{{ minEdu.additional_literature|default_if_none:"" }}</textarea>
    </div>
    <!--ДОДЕЛАТЬ TODO-->
    <div class="interner-resource">
        <label for="interner-resource"><h3>Интернет ресурсы</h3></label>

        <div name="interner-resource">
            <div class="resource-name">
                <label for="name">Наименование интернет ресурса</label>
                <input type="text" class="form-control">
            </div>
            <div class="resource-link">
                <label for="link">Интернет ссылка на ресурс</label>
                <input type="text" class="form-control">
            </div>
        </div>
    </div>
</div>